name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: compile
      run: g++ ./src/gasMain.cpp ./include/gasHeader.hpp -o gas --std=c++17
    - name: test
      run: g++ ./contributing/testing/test.cpp ./include/gasHeader.hpp ./contributing/testing/catch.hpp --std=c++17
